### ISSUE TITLE
RTC

### ISSUE THREAD

**Issue by trteodor** [embeddedalpha/STM32F411CEU6#1]
File: https://github.com/embeddedalpha/STM32F411CEU6/blob/main/RTC/RTC.c
Line: 111:  	monthu = (d & 0xf00) >> 12;
Should be: monthu = (d & 0xf00) >> 8;

;)

**Comment by embeddedalpha** [comment]
Great catch! Issue is fixed now. My notifications were off so I couldn't fix it right away. Kindly take a look at my other repos.
