### ISSUE TITLE
I2C transmit buffer not correctly iterating over the buffer

### ISSUE THREAD

**Issue by Eqqm4n** [embeddedalpha/STM32F411CEU6#2]
This function in I2C.c :
```
void I2C_Master_Send_Buffer(I2C_Config I2C, uint8_t *data, int length)
{
	for(int i = 0; i < length; i++)
	{
		while((I2C.I2C -> SR1 & 0x80) == 0){}
		I2C.I2C -> DR = data;
		while((I2C.I2C -> SR1 & 0x80) == 0){}
	}
}

```
Is supposed to iterate over the elements in the buffer, but doesn't, and it also fails to de-reference the pointer to the data.  This code did not even compile under Segger Embedded Studio and needs to be changed to :
```
I2C.I2C -> DR = data[i];
```

**Comment by embeddedalpha** [comment]
Ah yes, good catch. Will update soon.

**Comment by embeddedalpha** [comment]
Issue is fixed now! Please continue testing these files. Also take a look at STM32F4 repos.

**Comment by embeddedalpha** [comment]
Closing issue
